### ISSUE TITLE
Support for opensearch serverless auth_type  config

### ISSUE THREAD

**Issue by assafcoh** [opensearch-project/logstash-input-opensearch#53]
We would like support for aws opensearch serverless just like in the logstash-output-plugin

Our scenario requires migrating data from aws opensearch serverless to opensearch provisioned cluster.
Opensearch serverless does not support user/password access authorization. It supports access by iam users/roles.

When using latest logstach-input-opensearch plugin with config below we get error "auth_type" not recognized for opensearch"

input {
    opensearch {
        ecs_compatibility => disabled
        index => "endpoint_discovery"
        hosts => "https://123456.us-east-1.aoss.amazonaws.com:443"
        auth_type => {
            type => 'aws_iam'
            aws_access_key_id => 'xxxxxxxxxxxxxxxxxx'
            aws_secret_access_key => 'yyyyyyyyyyyyy'
            region => 'us-east-1'
            service_name => 'aoss'
            }
        legacy_template => false
        default_server_major_version => 2
    }
}

It would be great if auth_type config support will be added, just like for logstach-output-opensearch plugin

**Comment by JacobSiegle** [comment]
Duplicate - https://github.com/opensearch-project/logstash-input-opensearch/issues/24

**Comment by dblock** [comment]
Closing as dup.
